/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 予約を作成する */
        post: operations["createReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/{reservationId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 予約をキャンセルする(RSV-K追記) */
        post: operations["cancelReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会議室の空いている時間帯を確認する(RSV-A追記) */
        get: operations["getRoomAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms/{roomId}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会議室の予約ルール(営業時間・定員・最小予約時間)を確認する(RSV-R追記) */
        get: operations["getRoomReservationRules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 会議室の一覧を確認する(RSV-L追記) */
        get: operations["listRooms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateReservationRequest: {
            /** @description 会議室ID */
            roomId: string;
            /** @description 予約する人のID */
            reserverId: string;
            /**
             * Format: date
             * @description 予約日
             */
            date: string;
            /** @description 開始時刻(その日の時刻) */
            startTime: string;
            /** @description 終了時刻(その日の時刻)。時間帯は半開区間で、終了時刻ちょうどは占有に含まない */
            endTime: string;
            /** @description 利用人数 */
            attendeeCount: number;
        };
        ReservationResponse: {
            reservationId: string;
            roomId: string;
            reserverId: string;
            /** Format: date */
            date: string;
            startTime: string;
            endTime: string;
            attendeeCount: number;
        };
        CancelReservationRequest: {
            /** @description キャンセルを実行する人のID。予約した本人と一致しなければ403 */
            reserverId: string;
        };
        CancelledReservationResponse: {
            reservationId: string;
            roomId: string;
            reserverId: string;
            /** Format: date */
            date: string;
            startTime: string;
            endTime: string;
            attendeeCount: number;
            /**
             * Format: date-time
             * @description キャンセルが実行された日時
             */
            cancelledAt: string;
        };
        AvailabilityResponse: {
            roomId: string;
            /** Format: date */
            date: string;
            /** @description 空いている時間帯の一覧。開始時刻の昇順で返る。予約が一件もない日は営業時間そのもの 1件になり、全て埋まっている日は空配列になる */
            availableSlots: components["schemas"]["AvailableTimeSlot"][];
        };
        AvailableTimeSlot: {
            /** @description 空いている時間帯の開始時刻 */
            startTime: string;
            /** @description 空いている時間帯の終了時刻。時間帯は半開区間で、終了時刻ちょうどは空き時間に含まない */
            endTime: string;
        };
        RoomRulesResponse: {
            roomId: string;
            /** @description 営業時間の開始時刻(会議室ごとの現在の設定) */
            businessHoursStart: string;
            /** @description 営業時間の終了時刻(会議室ごとの現在の設定) */
            businessHoursEnd: string;
            /** @description 定員(会議室ごとの現在の設定) */
            capacity: number;
            /** @description 予約可能な最小時間(分)。システム共通の値で、会議室によらず同じ(RSV-C-05/RSV-A-05のルールと同一箇所を参照) */
            minReservationDurationMinutes: number;
        };
        RoomListResponse: {
            /** @description 会議室の一覧。name(表示名)の昇順で返る。会議室が一件も登録されていない場合は空配列 */
            rooms: components["schemas"]["RoomSummary"][];
        };
        RoomSummary: {
            /** @description 会議室ID */
            roomId: string;
            /** @description 会議室の表示名(例"会議室A")。/rooms/{roomId}/rulesには含まれない(役割分担はadr/0007) */
            name: string;
            /** @description 営業時間の開始時刻(会議室ごとの現在の設定) */
            businessHoursStart: string;
            /** @description 営業時間の終了時刻(会議室ごとの現在の設定) */
            businessHoursEnd: string;
            /** @description 定員(会議室ごとの現在の設定) */
            capacity: number;
        };
        ProblemResponse: {
            /** @description 拒否理由コード。TIME_SLOT_CONFLICT(重なり) / TOO_SHORT(30分未満) / INVALID_TIME_SLOT(逆転・同一時刻) / OUTSIDE_BUSINESS_HOURS(営業時間外) / EXCEEDS_CAPACITY(定員超過) / NOT_RESERVER(本人以外のキャンセル) / CANCEL_DEADLINE_PASSED(開始15分前超過) / ALREADY_CANCELLED(キャンセル済み) / RESERVATION_NOT_FOUND(予約なし) / ROOM_NOT_FOUND(会議室が存在しない) ※RSV-K改訂でキャンセル系4コードを追記(人間裁定に基づく承認済みテキストの改訂) ※RSV-A改訂(承認済み 2026-07-16): ROOM_NOT_FOUNDを追記。既存9コードの意味・割り当ては無変更 ※RSV-L(承認済み 2026-07-27): 新規コードなし。GET /roomsに拒否レスポンスが無いため */
            code: string;
            /** @description 人間が読める説明 */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createReservation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "roomId": "room-a",
                 *       "reserverId": "user-001",
                 *       "date": "2026-07-14",
                 *       "startTime": "10:00",
                 *       "endTime": "11:00",
                 *       "attendeeCount": 4
                 *     }
                 */
                "application/json": components["schemas"]["CreateReservationRequest"];
            };
        };
        responses: {
            /** @description 予約が作成された */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reservationId": "rsv-123",
                     *       "roomId": "room-a",
                     *       "reserverId": "user-001",
                     *       "date": "2026-07-14",
                     *       "startTime": "10:00",
                     *       "endTime": "11:00",
                     *       "attendeeCount": 4
                     *     }
                     */
                    "application/json": components["schemas"]["ReservationResponse"];
                };
            };
            /** @description 時間帯が既存の予約と重なっている(室×時間帯の排他的占有に違反) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TIME_SLOT_CONFLICT",
                     *       "message": "時間帯が既存の予約と重なっています"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 予約単体のルール違反(30分未満・時刻の逆転/同一・営業時間外・定員超過) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "TOO_SHORT",
                     *       "message": "予約は30分以上でなければなりません"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    cancelReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description キャンセル対象の予約ID */
                reservationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "reserverId": "user-sato"
                 *     }
                 */
                "application/json": components["schemas"]["CancelReservationRequest"];
            };
        };
        responses: {
            /** @description 予約がキャンセルされた(RSV-K-01/04/05) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "reservationId": "rsv-123",
                     *       "roomId": "room-a",
                     *       "reserverId": "user-sato",
                     *       "date": "2026-07-14",
                     *       "startTime": "10:00",
                     *       "endTime": "11:00",
                     *       "attendeeCount": 4,
                     *       "cancelledAt": "2026-07-14T09:30:00+09:00"
                     *     }
                     */
                    "application/json": components["schemas"]["CancelledReservationResponse"];
                };
            };
            /** @description 予約した本人ではない(RSV-K-02) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "NOT_RESERVER",
                     *       "message": "予約した本人のみキャンセルできます"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 予約が存在しない(RSV-K-09) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "RESERVATION_NOT_FOUND",
                     *       "message": "予約が存在しません"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 既にキャンセルされている(RSV-K-08) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ALREADY_CANCELLED",
                     *       "message": "この予約は既にキャンセルされています"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
            /** @description 開始15分前を過ぎている(RSV-K-06/07) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "CANCEL_DEADLINE_PASSED",
                     *       "message": "開始15分前を過ぎているためキャンセルできません"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getRoomAvailability: {
        parameters: {
            query: {
                /** @description 確認したい日付 */
                date: string;
            };
            header?: never;
            path: {
                /** @description 空き状況を確認する会議室ID */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 空いている時間帯の一覧が返る(RSV-A-01〜06)。予約が一件もない日は営業時間そのもの1件、全て埋まっている日は空配列。予約可能な空きのみ(最小予約時間未満の隙間は除外、RSV-A-05) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "roomId": "room-a",
                     *       "date": "2026-07-14",
                     *       "availableSlots": [
                     *         {
                     *           "startTime": "09:00",
                     *           "endTime": "10:00"
                     *         },
                     *         {
                     *           "startTime": "11:00",
                     *           "endTime": "18:00"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description 会議室が存在しない(RSV-A-07) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ROOM_NOT_FOUND",
                     *       "message": "会議室が存在しません"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    getRoomReservationRules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 予約ルールを確認する会議室ID */
                roomId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 予約ルールが返る(RSV-R-01/02)。営業時間・定員は会議室ごとの現在の設定、最小予約時間はシステム共通の値 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "roomId": "room-a",
                     *       "businessHoursStart": "09:00",
                     *       "businessHoursEnd": "18:00",
                     *       "capacity": 6,
                     *       "minReservationDurationMinutes": 30
                     *     }
                     */
                    "application/json": components["schemas"]["RoomRulesResponse"];
                };
            };
            /** @description 会議室が存在しない(RSV-R-03) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ROOM_NOT_FOUND",
                     *       "message": "会議室が存在しません"
                     *     }
                     */
                    "application/json": components["schemas"]["ProblemResponse"];
                };
            };
        };
    };
    listRooms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 会議室の一覧が返る。並び順はname(表示名)の昇順。会議室が一件も無い場合は空配列。受け入れシナリオは実装スライスでtesterがRSV-Lとして起こす(adr/0007を参照) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "rooms": [
                     *         {
                     *           "roomId": "room-a",
                     *           "name": "会議室A",
                     *           "businessHoursStart": "09:00",
                     *           "businessHoursEnd": "18:00",
                     *           "capacity": 6
                     *         },
                     *         {
                     *           "roomId": "room-b",
                     *           "name": "会議室B",
                     *           "businessHoursStart": "08:00",
                     *           "businessHoursEnd": "20:00",
                     *           "capacity": 10
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["RoomListResponse"];
                };
            };
        };
    };
}
